//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by huiren on 16/10/20.
//  Copyright © 2016年 xkl. All rights reserved.
//

#import "MessagesViewController.h"
#import "MessageTableViewCell.h"
#import "MessageCollectionViewCell.h"
#import "PrefixHeader.pch"

@interface MessagesViewController ()<UITableViewDataSource, UITableViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate>
@property (weak, nonatomic) IBOutlet UITableView *tableView;
@property (weak, nonatomic) IBOutlet UICollectionView *collectionView;
@property (strong, nonatomic) UICollectionViewFlowLayout * itemFlowLayout;
@property BOOL isSelect;

@end

@implementation MessagesViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self.tableView registerNib:[UINib nibWithNibName:@"MessageTableViewCell" bundle:nil] forCellReuseIdentifier:@"table"];
    self.tableView.separatorStyle = NO;
    self.tableView.tableFooterView = [[UIView alloc] init];
    
    [self.collectionView registerNib:[UINib nibWithNibName:@"MessageCollectionViewCell" bundle:nil] forCellWithReuseIdentifier:@"collection"];
    CGFloat spaace = [UIScreen mainScreen].bounds.size.width * 0.8 - (4 + 1) * 10 / 4;
    self.itemFlowLayout.itemSize = CGSizeMake(spaace, spaace);
    
    self.isSelect = NO;
}


#pragma mark - Conversation Handling
/*
 ** 以下是系统默认提供的涉及到iMessageApp生命周期的方法，暂时没有用到
 */

/*
 启动过程
 - Message Extension启动
 */
-(void)didBecomeActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the inactive to active state.
    // This will happen when the extension is about to present UI.
    
    // Use this method to configure the extension and restore previously stored state.
}

/*
 销毁过程
 - Message Extension被系统销毁
 */
-(void)willResignActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
}

/*
 other
 */
-(void)didReceiveMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
}

-(void)didStartSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user taps the send button.
}

-(void)didCancelSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
}

/*
 唤起过程
 - 唤起过程发生在MSMessagesAppViewController的presentationStyle发生变化时。
 */
-(void)willTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called before the extension transitions to a new presentation style.
    
    // Use this method to prepare for the change in presentation style.
}

-(void)didTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called after the extension transitions to a new presentation style.
    
    // Use this method to finalize any behaviors associated with the change in presentation style.
}

#pragma mark -
#pragma mark - UITableView
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return 8;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    MessageTableViewCell * cell = [tableView dequeueReusableCellWithIdentifier:@"table"];
    NSString * imageName = [NSString stringWithFormat:@"%@_1.gif", @(indexPath.row + 1)];
    NSString * filePath = [[NSBundle bundleWithPath:[[NSBundle mainBundle] bundlePath]] pathForResource:imageName ofType:@""];
    NSData * imageData = [NSData dataWithContentsOfFile:filePath];
    cell.iMessageImageView.image = [UIImage sd_animatedGIFWithData:imageData];
    
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    NSIndexPath * selectIndexPath = [NSIndexPath indexPathForRow:0 inSection:indexPath.row];
    self.isSelect = YES;
    [self.collectionView selectItemAtIndexPath:selectIndexPath animated:YES scrollPosition:UICollectionViewScrollPositionTop];
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 60;
}

#pragma mark -
#pragma mark - UICollectionView
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView
{
    return 8;
}

- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section
{
    return 9;
}

- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    MessageCollectionViewCell * cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"collection" forIndexPath:indexPath];
    cell.iMessageImageView.image = [UIImage imageNamed:[NSString stringWithFormat:@"%@_%@.gif", @(indexPath.section + 1), @(indexPath.item + 1)]];
    NSString * imageName = [NSString stringWithFormat:@"%@_%@.gif", @(indexPath.section + 1), @(indexPath.item + 1)];
    NSString * filePath = [[NSBundle bundleWithPath:[[NSBundle mainBundle] bundlePath]] pathForResource:imageName ofType:@""];
    NSData * imageData = [NSData dataWithContentsOfFile:filePath];
    cell.iMessageImageView.image = [UIImage sd_animatedGIFWithData:imageData];
    
    return cell;
}

- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
    /*
     ** 发送表情
     */
    
    //1.获取当前获取的消息会话
    MSConversation * activeConversation;
    if (self.activeConversation) {
        activeConversation = self.activeConversation;
    } else {
        //优雅的退出，从而避免发生崩溃
        return;
    }
    
    //2.获取表情资源url
    NSString * imageName = [NSString stringWithFormat:@"%@_%@.gif", @(indexPath.section + 1), @(indexPath.item + 1)];
    NSURL * url;
    if (imageName) {
        url = [[NSBundle mainBundle] URLForResource:imageName withExtension:@""];
    } else {
        return;
    }
    
    //3发送附件(必须是fileUrl)
    [activeConversation insertAttachment:url withAlternateFilename:@"" completionHandler:nil];
}

//定义每个Item 的大小
-(CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath
{
    return CGSizeMake(60, 60);
}

#pragma mark -
#pragma mark - UIScrollView
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView
{
    if (scrollView == self.collectionView) {
        self.isSelect = NO;
    }
}

- (void)scrollViewDidScroll:(UIScrollView *)scrollView
{
    if (scrollView == self.collectionView && !self.isSelect) {
        CGFloat spaace = [UIScreen mainScreen].bounds.size.width * 0.8 - (4 + 1) * 10 / 4 + 10;
        NSInteger index = (NSInteger)round(scrollView.contentOffset.y / spaace / 3);
        NSIndexPath * indePath = [NSIndexPath indexPathForRow:MAX(MIN(index, 7), 0) inSection:0];
        [self.tableView selectRowAtIndexPath:indePath animated:YES scrollPosition:UITableViewScrollPositionTop];
        [self.tableView scrollToRowAtIndexPath:indePath atScrollPosition:UITableViewScrollPositionMiddle animated:YES];
    }
}

@end
